# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMainApp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget = MPL_WIDGET(self.centralwidget)
        self.mplwidget.setObjectName("mplwidget")
        self.horizontalLayout.addWidget(self.mplwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Sittings = QtWidgets.QDockWidget(MainWindow)
        self.Sittings.setObjectName("Sittings")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_theta0 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_theta0.setObjectName("label_theta0")
        self.verticalLayout.addWidget(self.label_theta0)
        self.SpinBox_theta0 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_theta0.setDecimals(0)
        self.SpinBox_theta0.setMinimum(-90.0)
        self.SpinBox_theta0.setMaximum(90.0)
        self.SpinBox_theta0.setSingleStep(1.0)
        self.SpinBox_theta0.setProperty("value", 0.0)
        self.SpinBox_theta0.setObjectName("SpinBox_theta0")
        self.verticalLayout.addWidget(self.SpinBox_theta0)
        self.slider_theta0 = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_theta0.setMinimum(-90)
        self.slider_theta0.setMaximum(90)
        self.slider_theta0.setSingleStep(10)
        self.slider_theta0.setPageStep(1)
        self.slider_theta0.setProperty("value", 0)
        self.slider_theta0.setSliderPosition(0)
        self.slider_theta0.setOrientation(QtCore.Qt.Horizontal)
        self.slider_theta0.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_theta0.setTickInterval(50)
        self.slider_theta0.setObjectName("slider_theta0")
        self.verticalLayout.addWidget(self.slider_theta0)
        self.label_y0 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_y0.setObjectName("label_y0")
        self.verticalLayout.addWidget(self.label_y0)
        self.SpinBox_y0 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_y0.setDecimals(1)
        self.SpinBox_y0.setMinimum(-100.0)
        self.SpinBox_y0.setMaximum(100.0)
        self.SpinBox_y0.setSingleStep(1.0)
        self.SpinBox_y0.setProperty("value", 0.0)
        self.SpinBox_y0.setObjectName("SpinBox_y0")
        self.verticalLayout.addWidget(self.SpinBox_y0)
        self.slider_y0 = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_y0.setMinimum(-100)
        self.slider_y0.setMaximum(100)
        self.slider_y0.setSingleStep(1)
        self.slider_y0.setProperty("value", 2)
        self.slider_y0.setOrientation(QtCore.Qt.Horizontal)
        self.slider_y0.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_y0.setTickInterval(10)
        self.slider_y0.setObjectName("slider_y0")
        self.verticalLayout.addWidget(self.slider_y0)
        self.label_n2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_n2.setObjectName("label_n2")
        self.verticalLayout.addWidget(self.label_n2)
        self.SpinBox_n2 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_n2.setDecimals(1)
        self.SpinBox_n2.setMinimum(1.0)
        self.SpinBox_n2.setMaximum(20.0)
        self.SpinBox_n2.setSingleStep(1.0)
        self.SpinBox_n2.setProperty("value", 10.0)
        self.SpinBox_n2.setObjectName("SpinBox_n2")
        self.verticalLayout.addWidget(self.SpinBox_n2)
        self.slider_n2 = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_n2.setMinimum(1)
        self.slider_n2.setMaximum(20)
        self.slider_n2.setProperty("value", 10)
        self.slider_n2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_n2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_n2.setTickInterval(10)
        self.slider_n2.setObjectName("slider_n2")
        self.verticalLayout.addWidget(self.slider_n2)
        self.label_r = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_r.setObjectName("label_r")
        self.verticalLayout.addWidget(self.label_r)
        self.SpinBox_r = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_r.setDecimals(1)
        self.SpinBox_r.setMinimum(-200.0)
        self.SpinBox_r.setMaximum(200.0)
        self.SpinBox_r.setSingleStep(400.0)
        self.SpinBox_r.setProperty("value", -200.0)
        self.SpinBox_r.setObjectName("SpinBox_r")
        self.verticalLayout.addWidget(self.SpinBox_r)
        self.slider_r = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_r.setMinimum(-200)
        self.slider_r.setMaximum(200)
        self.slider_r.setSingleStep(400)
        self.slider_r.setPageStep(400)
        self.slider_r.setProperty("value", -200)
        self.slider_r.setOrientation(QtCore.Qt.Horizontal)
        self.slider_r.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_r.setTickInterval(10)
        self.slider_r.setObjectName("slider_r")
        self.verticalLayout.addWidget(self.slider_r)
        self.label_n1 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_n1.setObjectName("label_n1")
        self.verticalLayout.addWidget(self.label_n1)
        self.SpinBox_n1 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.SpinBox_n1.setDecimals(1)
        self.SpinBox_n1.setMinimum(1.0)
        self.SpinBox_n1.setMaximum(20.0)
        self.SpinBox_n1.setProperty("value", 10.0)
        self.SpinBox_n1.setObjectName("SpinBox_n1")
        self.verticalLayout.addWidget(self.SpinBox_n1)
        self.slider_n1 = QtWidgets.QSlider(self.dockWidgetContents)
        self.slider_n1.setMinimum(1)
        self.slider_n1.setMaximum(20)
        self.slider_n1.setProperty("value", 10)
        self.slider_n1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_n1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_n1.setTickInterval(10)
        self.slider_n1.setObjectName("slider_n1")
        self.verticalLayout.addWidget(self.slider_n1)
        self.Sittings.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Sittings)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Sittings.setWindowTitle(_translate("MainWindow", "Sittings"))
        self.label_theta0.setText(_translate("MainWindow", "incidence angle"))
        self.label_y0.setText(_translate("MainWindow", "initial point"))
        self.label_n2.setText(_translate("MainWindow", "Lens refractive index*10"))
        self.label_r.setText(_translate("MainWindow", "Radius of curvature"))
        self.label_n1.setText(_translate("MainWindow", "Environmental refractive index*10"))

from mplwidget import MPL_WIDGET

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

